apache/karaf

shell/core/src/test/java/org/apache/karaf/shell/support/table/ShellTableTest.java
Tested on Win7x64 and Ubuntu 14
=> [KARAF-3755] shell.support.table.ShellTableTest breaked build on Windows

features/core/src/main/java/org/apache/karaf/features/internal/BundleManager.java
https://issues.apache.org/jira/browse/KARAF-2882
=> don't wait for services for default url handler protocols

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/GenerateDescriptorMojo.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/utils/MojoSupport.java
KARAF-3963: add more information to the mojo documentation for features-generate-descriptor.
=> KARAF-3963: add some more sauce to the documentation 

manual/src/main/webapp/developers-guide/debugging.conf
Patch documents Debug environment variables
=> KARAF-3990 - Document Debug Environment Variables

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/AssemblyMojo.java
=> KARAF-4079: Added support for src/main/resources/assembly to overwrite config files e.g. etc/*

kar/src/main/java/org/apache/karaf/kar/internal/KarServiceImpl.java
collects kars with unresolved dependencies to retry them during the next
deployment or after a short timeout
=> https://issues.apache.org/jira/browse/KARAF-3443

assemblies/features/enterprise/src/main/feature/feature.xml, pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-3879
Andrea
=> [KARAF-3879] jdbc feature should installs pax-jdbc feature

pom.xml
Hi,
This PR is related to
https://issues.apache.org/jira/browse/KARAF-4096
Andrea
=> [KARAF-4096] Upgrade Jolokia to version 1.3.2

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4126
Andrea
=> [KARAF-4126] Upgrade Cglib bundle to version 3.1_1

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4135
For the moment I just upgrade the dependency.
Andrea
=> [KARAF-4135] Upgrade commons-collections to version 3.2.2

bundle/core/src/main/java/org/apache/karaf/bundle/core/internal/BundleSelectorImpl.java, itests/src/test/java/org/apache/karaf/itests/JaasSshCommandSecurityTest.java
Hi all,
https://issues.apache.org/jira/browse/KARAF-4119
Andrea
=> [KARAF-4119] la outputs results twice

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/AbstractFeatureMojo.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/AddToRepositoryMojo.java
=> Fix for KARAF-4082

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4149
Andrea
=> [KARAF-4149] Upgrade to Derby 10.12.1.1

profile/src/main/java/org/apache/karaf/profile/assembly/Builder.java
Hi all,
https://issues.apache.org/jira/browse/KARAF-4134
Andrea
=> [KARAF-4134] karaf-maven-plugin mixes up prerequisities

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4151
Andrea
=> [KARAF-4151] Upgrade Felix Coordinator to version 1.0.2

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4185
Andrea
=> [KARAF-4185] Upgrade Pax-url to version 2.4.4

shell/core/src/main/java/org/apache/karaf/shell/impl/action/command/ArgumentCompleter.java
Hi all,
https://issues.apache.org/jira/browse/KARAF-4184
Andrea
=> [KARAF-4184] ArgumentCompleter has incorrect check for enum type

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4196
Andrea
=> [KARAF-4196] Upgrade Cglib to version 3.2.0

client/src/main/java/org/apache/karaf/client/ClientConfig.java
Karaf client should allow passing arguments to command
=> KARAF-3390

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4227
Andrea
=> [KARAF-4227] Upgrade to Pax-exam 4.8.0

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4286
Andrea
=> [KARAF-4286] Upgrade Felix Utils to version 1.8.2

pom.xml
Hi all,
https://issues.apache.org/jira/browse/KARAF-4287
Andrea
=> [KARAF-4287] Upgrade Felix Fileinstall to version 3.5.2

features/command/src/main/java/org/apache/karaf/features/command/InstallFeatureCommand.java, features/core/src/main/java/org/apache/karaf/features/FeaturesService.java, features/core/src/main/java/org/apache/karaf/features/internal/service/FeaturesServiceImpl.java, itests/src/test/java/org/apache/karaf/itests/FeatureTest.java
Feature upgrade implemetation via install command option.
=> [KARAF-129] Add upgrade option to Feature install command

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/utils/MojoSupport.java
https://issues.apache.org/jira/browse/KARAF-4288
=> KARAF-4288 - pass custom settings.xml onto pax-url-aether

management/server/src/main/java/org/apache/karaf/management/KarafMBeanServerGuard.java, management/server/src/test/java/org/apache/karaf/management/KarafMBeanServerGuardTest.java
(cherry picked from commit 3e83c1d45a6dc9c4a06ba4efed47e2de2ec36cd2)
=> [KARAF-4348] Correct ordering of wildcard PID for RBAC

scr/command/src/main/java/org/apache/karaf/scr/command/ScrCommandConstants.java
Sorry , I didn't know if I override my commit it would delete the PR..
=> KARAF-4454 - Resolve scr:list conflict between gogo and Karaf

assemblies/features/framework/src/main/filtered-resources/resources/bin/client, assemblies/features/framework/src/main/filtered-resources/resources/bin/instance, assemblies/features/framework/src/main/filtered-resources/resources/bin/shell, assemblies/features/framework/src/main/filtered-resources/resources/bin/start, assemblies/features/framework/src/main/filtered-resources/resources/bin/status, assemblies/features/framework/src/main/filtered-resources/resources/bin/stop, assemblies/features/framework/src/main/resources/resources/bin/karaf
(cherry picked from commit 5bbaf71814df514b112cbe8cd73ba57fefdc869f)
=> [KARAF-4628] [KARAF-4564] Fix unix startup scripts

log/src/main/java/org/apache/karaf/log/core/internal/KarafLogEvent.java, log/src/main/java/org/apache/karaf/log/core/internal/layout/PatternParser.java
See https://issues.apache.org/jira/browse/KARAF-5124
@jbonofre here is the master branch pr requested.
=> KARAF-5124 Fix location logging in Karaf console

assemblies/features/base/src/main/resources/resources/etc/org.ops4j.pax.url.mvn.cfg, pom.xml
Quick PR to test the repo cleanup on Jenkins.
=> [KARAF-5294] Cleanup unused Maven repositories

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/GenerateDescriptorMojo.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/utils/MojoSupport.java
OpenDaylight is a heavy user of feature generation and is using 4.0.9 branch currently. These fixes speed up build time considerably and should be backported.
=> Backport plugin optimizations from master

management/server/src/main/java/org/apache/karaf/management/KarafMBeanServerGuard.java
=> Remove unnecessary code

tooling/karaf-services-maven-plugin/src/main/java/org/apache/karaf/tooling/tracker/GenerateServiceMetadata.java
See
https://mhus.de/2017/11/02/karaf-maven-tools-performance-issue-in-eclips
e-ide/ for details
=> Fix performance issue generating service metadata, change logging

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/VerifyMojo.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/utils/MojoSupport.java
This commit rollbacks/moves changes made in KARAF-4288 to verify mojo.
=> KARAF-5585 Do not provide maven settings for pax url if they are gone.

shell/core/src/main/java/org/apache/karaf/shell/impl/console/SessionFactoryImpl.java, shell/core/src/main/java/org/apache/karaf/shell/impl/console/commands/Procedural.java
This is a temporary commit until the real fix is moved into gogo (to provide better syntax highlighting of this new syntax).
=> [KARAF-5629] Improve syntax of procedural functions

assemblies/features/standard/src/main/feature/feature.xml, manual/pom.xml, pom.xml
Adding a documentation feature in order to published the generated manual in html with the http service.
=> [KARAF-5649] Add a feature for the manual

assemblies/features/enterprise/src/main/feature/feature.xml, itests/src/test/java/org/apache/karaf/itests/features/EnterpriseFeaturesTest.java, pom.xml
* https://issues.apache.org/jira/browse/KARAF-5679
=> [KARAF-5679] Upgrade to Hibernate Validator 6.0.9.Final

wrapper/src/main/java/org/apache/karaf/wrapper/commands/Install.java, wrapper/src/main/resources/org/apache/karaf/wrapper/internal/unix/karaf-service
Add display of HP-UX service instructions + fix bad usage of shell commands in karaf-service script when used on HPUX platform
=> [KARAF-5765] Enhance karaf-service on HP-UX 

bundle/core/src/main/java/org/apache/karaf/bundle/command/Classes.java
Notes:
* added the "exported" status of packages
* getExports was copied from PackageServiceImpl and could be refactored
* bundle ID is displayed whenever there are more than one bundles selected (including the simple bundle:classes case)
=> [KARAF-5752] Add bundle ID in bundle:classes output

pom.xml
See: https://maven.apache.org/security-plexus-archiver.html
=> Updating some maven plugin versions

features/core/src/main/java/org/apache/karaf/features/management/FeaturesServiceMBean.java, features/core/src/main/java/org/apache/karaf/features/management/codec/JmxFeature.java, features/core/src/main/java/org/apache/karaf/features/management/codec/JmxRepository.java, features/core/src/test/java/org/apache/karaf/features/management/codec/JmxFeatureTest.java, features/core/src/test/java/org/apache/karaf/features/management/codec/JmxRepositoryTest.java
https://issues.apache.org/jira/browse/KARAF-5786
=> [KARAF-5786] Add blacklisted key to JmxFeature & JmxRepository CompositeData

pom.xml
Update the Surefire plugin (required for Java 10) + update the apache parent version
=> Update surefire + apache parent versions

manual/src/main/asciidoc/user-guide/directory-structure.adoc
@jbonofre : Maybe merge before releasing 4.2.1
=> NO-JIRA: Fix small typo in documentation

profile/src/main/java/org/apache/karaf/profile/assembly/Builder.java
Now it use the existing file and performs the specified changes.
Signed-off-by: van Sabben <4246302+vanSabben@users.noreply.github.com>
=> [KARAF-5781] Properties edit doesn't conserve the existing ones. (On master)

shell/core/src/main/java/org/apache/karaf/shell/impl/console/ConsoleSessionImpl.java
Fix NullPointerException when starting shell using bin/shell
See Jira: https://issues.apache.org/jira/browse/KARAF-5887
=> [KARAF-5887] Fix NPE on ConsoleSessionImpl

pom.xml, webconsole/console/src/main/resources/res/karaf/ui/webconsole.css
Update to Apache Felix Webconsole 4.3.8 and latest jQuery UI 1.12.1.
I also made some changes on the CSS nav menu.
=> [KARAF-5906] Update to Apache Felix Webconsole 4.3.8

jaas/modules/src/main/java/org/apache/karaf/jaas/modules/publickey/PublickeyLoginModule.java
It should use the BackingEngine interface property instead.
=> The publickey JAAS module has a dependency on the properties JAAS module

pom.xml, specs/pom.xml, tooling/pom.xml
Upgrade Maven versions + also consolidate on a single maven plugin version.
=> Upgrade Maven versions

features/core/src/main/java/org/apache/karaf/features/internal/service/FeaturesProcessingSerializer.java, util/src/main/java/org/apache/karaf/util/XmlUtils.java
Set the secure processing feature on all SAXParserFactory instances.
=> Set the secure processing feature on all SAXParserFactory instances

log/src/main/java/org/apache/karaf/log/core/internal/LogServiceLog4j2XmlImpl.java, util/src/main/java/org/apache/karaf/util/XmlUtils.java
Set the secure processing feature on TransformerFactory instances
=> Set the secure processing feature on TransformerFactory instances

jaas/blueprint/jasypt/src/main/java/org/apache/karaf/jaas/blueprint/jasypt/handler/EncryptablePropertyPlaceholder.java, pom.xml
This PR will be completed once Aries Blueprint Core 1.10.1 & Aries Blueprint CM 1.3.1 will be released.
=> [KARAF-5942][KARAF-5943] Update to Aries Blueprint Core 1.10.1 & Aries Blueprint CM 1.3.1

main/src/test/java/org/apache/karaf/main/MainLockingTest.java, main/src/test/java/org/apache/karaf/main/MainStartTest.java
=> [KARAF-6044] Avoid verbose stack trace in main tests.

pom.xml
This PR will be complete once the Aries Proxy Impl 1.1.3 will be complete (currently on vote).
=> [KARAF-6041] Upgrade to Aries Proxy Impl 1.1.3

http/pom.xml, jaas/modules/pom.xml, pom.xml
Use a single version of httpclient
=> Use a single version of httpclient

kar/src/main/java/org/apache/karaf/kar/command/InstallKarCommand.java
Added UriCompleter to kar:install Command
=> Added kar:install Completion

main/src/main/java/org/apache/karaf/main/ConfigProperties.java, main/src/main/java/org/apache/karaf/main/Main.java, main/src/test/java/org/apache/karaf/main/MainLockingTest.java
Adding a new configuration to tolerate lock lost for surviving DB connectivity fluctuations.
=> KARAF-6037 Adding support to tolerate lock lost

manual/src/main/asciidoc/user-guide/failover.adoc
Minimal doc update for KARAF-6037.
=> Doc update for KARAF-6037

util/src/main/java/org/apache/karaf/util/jaas/JaasHelper.java
=> [KARAF-6156] Update JaasHelper to support extending Karaf JAAS (4.3.x)

features/core/src/main/java/org/apache/karaf/features/internal/service/FeaturesProcessorImpl.java
We take now the pattern from override.properties, which
matches best (i.e. has the biggest length), not the last one
=> [KARAF-6183] Fix override for classified artifacts.

tooling/utils/src/main/java/org/apache/karaf/tools/utils/KarafPropertiesFile.java, tooling/utils/src/main/java/org/apache/karaf/tools/utils/SortedProperties.java
@jbonofre : Could you please have a look on this? Merci!
=> KARAF-6209: Add SortedProperties class to karaf tooling

maven/core/src/main/java/org/apache/karaf/maven/command/MavenConfigurationSupport.java
new Date() is just a thin wrapper around System.currentTimeMillis(). Using System.currentTimeMillis() can help speed up the system
=> KARAF-6235:use System.currentTimeMillis()

shell/ssh/src/main/java/org/apache/karaf/shell/ssh/Activator.java, shell/ssh/src/main/resources/OSGI-INF/metatype/metatype.xml
This fix is just for 4.2.x-fixes - it's included in https://github.com/apache/karaf/pull/911 for the master branch already.
=> Fixing an issue with SSH public key file

assemblies/features/standard/src/main/feature/feature.xml, instance/src/main/resources/org/apache/karaf/instance/resources/etc/org.apache.karaf.command.acl.feature.cfg, itests/test/src/test/filtered-resources/etc/feature.xml
feature:update is not a valid command
=> Remove feature:update ACL

pom.xml
I didn't bother with a JIRA as it's just a test dependency. Might as well update it to the same version as CXF, Camel, etc.
=> Updating Derby

shell/core/src/main/java/org/apache/karaf/shell/impl/console/HeadlessSessionImpl.java
when iterating over system properties
=> [KARAF-6337] Prevent ConcurrentModificationException

pom.xml
[KARAF-6371] Upgrade to Jetty 9.4.20.v20190813
=> [KARAF-6324] Upgrade to Pax Web 7.2.11

manual/src/main/asciidoc/developer-guide/karaf-maven-plugin.adoc, tooling/karaf-maven-plugin/src/it/test-transitive-as-dependency/pom.xml, tooling/karaf-maven-plugin/src/it/test-transitive-as-dependency/transitive-as-dependency-feature/src/main/feature/feature.xml, tooling/karaf-maven-plugin/src/it/test-transitive-as-dependency/transitive-as-dependency-module-e/pom.xml, tooling/karaf-maven-plugin/src/it/test-transitive-as-dependency/transitive-as-dependency-module-e/src/main/java/test/E.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/GenerateDescriptorMojo.java
See https://jira.apache.org/jira/browse/KARAF-6505.
=> [KARAF-6505] Allow override of the bundle's dependency attribute

examples/karaf-command-example/karaf-command-example-command/src/main/java/org/apache/karaf/examples/command/command/AddCommand.java, examples/karaf-jdbc-example/karaf-jdbc-example-command/src/main/java/org/apache/karaf/examples/jdbc/command/AddCommand.java, examples/karaf-jdbc-example/karaf-jdbc-example-provider/src/main/java/org/apache/karaf/examples/jdbc/provider/BookingServiceJdbcImpl.java, http/src/main/java/org/apache/karaf/http/core/internal/ProxyServlet.java, instance/src/main/java/org/apache/karaf/instance/core/internal/InstanceServiceImpl.java, jdbc/src/main/java/org/apache/karaf/jdbc/internal/JdbcServiceImpl.java, main/src/main/java/org/apache/karaf/main/Main.java, management/server/src/test/java/org/apache/karaf/management/KarafMBeanServerGuardTest.java, profile/src/main/java/org/apache/karaf/profile/assembly/Builder.java, scheduler/src/main/java/org/apache/karaf/scheduler/core/WhiteboardHandler.java, service/guard/src/test/java/org/apache/karaf/service/guard/impl/GuardProxyCatalogTest.java, service/guard/src/test/java/org/apache/karaf/service/guard/impl/GuardingEventHookTest.java, services/eventadmin/src/main/java/org/apache/felix/eventadmin/impl/adapter/BundleEventAdapter.java, shell/console/src/main/java/org/apache/karaf/shell/util/ShellUtil.java, shell/core/src/main/java/org/apache/karaf/shell/support/ShellUtil.java, shell/ssh/src/main/java/org/apache/karaf/shell/ssh/SshTerminal.java
This PR avoids some unnecessary autoboxing and uses the more efficient static valueOf contructors for numbers. It also fixes a ClassCastException in ProxyServlet if a ServletException is thrown.
=> Some minor efficiency improvements relating to parsing numbers

client/src/main/java/org/apache/karaf/client/Main.java, features/core/src/main/java/org/apache/karaf/features/internal/service/Blacklist.java, features/core/src/main/java/org/apache/karaf/features/internal/service/Overrides.java, http/src/main/java/org/apache/karaf/http/core/internal/ProxyServlet.java, jaas/boot/src/main/java/org/apache/karaf/jaas/boot/principal/ClientPrincipal.java, jaas/boot/src/main/java/org/apache/karaf/jaas/boot/principal/GroupPrincipal.java, obr/src/main/java/org/apache/karaf/obr/command/util/FileUtil.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/KarMojo.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/RunMojo.java
The fixes include:
- Make sure logging parameters are actually logged
- Fix a bug in the ProxyServlet to do with the location header
- Override equals in ClientPrincipal, as hashcode is already overwritten
- Fix GroupPrincipal.isMember
- Fix another instance of zip slip in RunMojo.
=> Some misc bug fixes

shell/ssh/src/main/java/org/apache/karaf/shell/ssh/Activator.java
=> [KARAF-6542] Fix sshd server refresh issue

assemblies/features/base/pom.xml, assemblies/features/base/src/main/filtered-resources/resources/etc/config.properties, assemblies/features/framework/pom.xml, assemblies/features/standard/src/main/feature/feature.xml, instance/src/main/resources/org/apache/karaf/instance/resources/etc/config.properties, instance/src/main/resources/org/apache/karaf/instance/resources/etc/org.apache.karaf.management.cfg, management/server/pom.xml, management/server/src/main/java/org/apache/karaf/management/ConnectorServerFactory.java, management/server/src/main/java/org/apache/karaf/management/JaasAuthenticator.java, management/server/src/main/java/org/apache/karaf/management/internal/Activator.java, management/server/src/main/java/org/apache/karaf/management/internal/JMXSecurityMBeanImpl.java, manual/src/main/asciidoc/user-guide/monitoring.adoc
This is a work in progress, I have to finalize the security layer and set `jmxmp` optional (`rmi` will remain the default protocol).
=> [KARAF-2925] Add jmxmp support on Karaf JMX service

features/core/src/main/java/org/apache/karaf/features/internal/download/impl/DownloadManagerHelper.java, features/core/src/test/java/org/apache/karaf/features/internal/download/impl/DownloadManagerHelperTest.java, profile/src/main/java/org/apache/karaf/profile/assembly/Builder.java, tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/AssemblyMojo.java
Continuation of https://github.com/apache/karaf/pull/879, but this time aiming to merge into master
=> [KARAF-6431] - Maven plugin feature to define custom bundle location prefixes

assemblies/features/base/src/main/filtered-resources/resources/bin/instance, assemblies/features/base/src/main/filtered-resources/resources/bin/instance.bat
Basically same issue as https://github.com/apache/karaf/pull/1045
=> Add osgi.core in the instance classpath (required by pax-logging)

assemblies/features/base/src/main/filtered-resources/resources/bin/inc
Signed-off-by: Rob Stryker <rob@oxbeef.net>
=> Version check error message is not completely accurate

README.md
additionally, using HTTPS for all links
=> [KARAF-6652] fixed broken links

pom.xml
Changes:
https://commons.apache.org/proper/commons-lang/changes-report.html#a3.10
=> [KARAF-6660] Update to commons-lang 3.10

pom.xml
Changes:
https://commons.apache.org/proper/commons-compress/changes-report.html#a1.20
=> [KARAF-6672] Upgrade to Commons Compress 1.20

pom.xml
=> [KARAF-6675] Upgrade Apache RAT plugin to 0.13

tooling/karaf-services-maven-plugin/src/main/java/org/apache/karaf/tooling/tracker/GenerateServiceMetadata.java
Small fixes in service plugin...
* fix filter to filter over group and artifact (groupId:artifactId) - backward compatible
* fix output to print service class - for better analysis
=> fix filter to filter over group and artifact

assemblies/features/base/src/main/filtered-resources/resources/bin/inc
Export JAVA_OPTS after adding EXTRA_JAVA_OPTS.
=> Export JAVA_OPTS after setting EXTRA_JAVA_OPTS

pom.xml
(cherry picked from commit 7077a8fbc2de6679f03853813d3403a50f5f8fa6)
=> [KARAF-6841] Upgrade to ant 1.10.8 (karaf-4.2.x)

pom.xml
(cherry picked from commit 6d8c033626bb50affcd628ede353f4299d6310e5)
=> [KARAF-6843] Upgrade to Felix SCR 2.1.24

assemblies/features/base/src/main/filtered-resources/resources/bin/inc
=> [KARAF-6887] Remove default JAVA_MAX_MEM JAVA_MIN_MEM 

assemblies/features/standard/src/main/feature/feature.xml, pom.xml
[KARAF-7031] Upgrade to Jetty 9.4.36.v20210114
=> [KARAF-7017] Upgrade to Pax Web 7.3.12

assemblies/features/standard/src/main/feature/feature.xml, pom.xml
[KARAF-7053] Upgrade to Jetty 9.4.38.v20210224
=> [KARAF-7054] Upgrade to Pax Web 7.3.13

pom.xml
https://commons.apache.org/proper/commons-lang/changes-report.html#a3.12.0
=> [KARAF-7073] Upgrade to commons-lang 3.12.0

assemblies/features/standard/src/main/feature/feature.xml, pom.xml
[KARAF-7119] Upgrade to Jetty 9.4.40.v20210413
=> [KARAF-7120] Upgrade to Pax Web 7.3.15

assemblies/features/base/src/main/filtered-resources/resources/bin/karaf.bat
I believe this was missed in https://github.com/apache/karaf/pull/1232
=> Add sasl export to karaf.bat

tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/VerifyMojo.java
Alternate solution to the same problem
=> [KARAF-7186] Fix feature:verify failing on bundle cleanup

pom.xml
(cherry picked from commit 790d663c0b11c0ed1c19db5c1d81932ca5f2d226)
=> [karaf-4.2.x][KARAF-7251] Upgrade to Felix Http 4.1.12

pom.xml
(cherry picked from commit cf178182c0dea5e07a04ae8663fed7c6dd14d5ca)
=> [karaf-4.2.x][KARAF-7252] Upgrade to Felix SCR 2.1.30

pom.xml
(cherry picked from commit 1eddb18aa3fa3ed22caa10312a710702abe5a9cf)
=> [karaf-4.2.x][KARAF-7253] Upgrade to Felix WebConsole 4.7.0

pom.xml
(cherry picked from commit b7f4509a0973c6d328cc0d8610d6e33fc8f4bfd5)
=> [karaf-4.2.x][KARAF-7254] Upgrade to JNA 5.9.0

pom.xml
Changes: https://jolokia.org/changes-report.html#a1.7.1
=> [KARAF-7296] Bump Jolokia to 1.7.1

SECURITY.md
It's good security practice to have a SECURITY.md in a github repo with details of supported versions and links to CVEs and how to report issues.
Feel free to modify as required.
=> Adding a SECURITY.md for Karaf

instance/src/main/resources/org/apache/karaf/instance/resources/etc/org.apache.karaf.shell.cfg, shell/ssh/src/main/java/org/apache/karaf/shell/ssh/Activator.java, shell/ssh/src/main/java/org/apache/karaf/shell/ssh/SshUtils.java
Signed-off-by: Sascha Vogt <s.vogt@seeburger.de>
=> [KARAF-7363] Allow restriction of signature algorithms for SSH server

RELEASE-NOTES.md
I think an important version change is missing from the current 4.3.7 release notes.
=> Update RELEASE-NOTES.md 4.3.7

pom.xml
see [KARAF-7434](https://issues.apache.org/jira/browse/KARAF-7434)
=> [KARAF-7434] upgrade Felix maven-bundle-plugin

assemblies/features/specs/src/main/feature/feature.xml, bom/pom.xml, pom.xml
[KARAF-7461] Upgrade to SMX jaxb-xjc 2.3.2_2
=> [KARAF-7460] Upgrade to SMX jaxb-runtime 2.3.2_3

features/command/src/main/java/org/apache/karaf/features/command/RepoAddCommand.java, features/command/src/main/java/org/apache/karaf/features/command/RepoRefreshCommand.java, features/command/src/main/java/org/apache/karaf/features/command/RepoRemoveCommand.java, features/command/src/test/java/org/apache/karaf/features/command/RepoAddCommandTest.java, features/command/src/test/java/org/apache/karaf/features/command/RepoListCommandTest.java, features/command/src/test/java/org/apache/karaf/features/command/RepoRefreshCommandTest.java, features/command/src/test/java/org/apache/karaf/features/command/RepoRemoveCommandTest.java, features/command/src/test/java/org/apache/karaf/features/command/RepositoryCommandTestBase.java
Hi, it's my first contribution so for starters I added some tests to feature repo commands.
If the PR is fine then I'll gladly submit more later.
=> KARAF-7552: add tests for feature:repo commands

features/command/src/main/java/org/apache/karaf/features/command/StatusCommand.java, features/command/src/main/java/org/apache/karaf/features/command/completers/FeatureVersionCompleter.java, itests/test/src/test/java/org/apache/karaf/itests/FeatureTest.java
It's a subtask from [KARAF-5193](https://issues.apache.org/jira/browse/KARAF-5193), which is pretty old but I think it's still relevant (at least feature:status was never implemented).
=> KARAF-7554 - add feature:status command

assemblies/features/standard/src/main/feature/feature.xml, instance/src/main/resources/org/apache/karaf/instance/resources/etc/org.apache.karaf.management.cfg, itests/test/src/test/filtered-resources/etc/feature.xml, manual/src/main/asciidoc/user-guide/remote.adoc
These typo fixes may be useful. :wink:
=> Fix "useful" typos

assemblies/features/base/src/main/filtered-resources/resources/bin/karaf.bat
Spaces are used for indentation in this file.
=> Fix karaf.bat indentation

archetypes/assembly/pom.xml, archetypes/blueprint/pom.xml, archetypes/bundle/pom.xml, archetypes/command/pom.xml, archetypes/feature/pom.xml, archetypes/kar/pom.xml, tooling/karaf-services-maven-plugin/src/main/java/org/apache/karaf/tooling/tracker/GenerateServiceMetadata.java
see https://issues.apache.org/jira/browse/KARAF-7637
=> [KARAF-7637] drop non-reproducible properties store

shell/core/src/main/java/org/apache/karaf/shell/support/table/Col.java
Account for multi-line cell contents when calculating cell width and clipping the text to maxSize. The cell contents might be either wrapped or originally split by the caller with \n characters
=> [KARAF-7678] Fix ShellTable multiline clipping

util/src/main/java/org/apache/karaf/util/config/PropertiesLoader.java
Mainly to show how to not have to update properties each 6 months (see #1723 for context)
=> Ensure jre and eecap config.properties properties can be computed for modern jvms

examples/karaf-config-example/README.md, examples/karaf-config-example/karaf-config-example-features/src/main/feature/feature.xml, examples/karaf-config-example/karaf-config-example-scr/src/main/java/org/apache/karaf/example/config/scr/MyComponent.java, itests/test/src/test/java/org/apache/karaf/itests/examples/ConfigExampleTest.java
- JSON configuration includes data types desribed in section 150.3.4 of the OSGi 8 Compendium
- Corrected XML schema definition of the features file.
=> KARAF-7708 Add example and test for JSON configuration

pom.xml
=> [KARAF-7761] Upgrade maven-resources-plugin to 3.3.1

pom.xml
=> [KARAF-7760] Upgrade maven-source-plugin to 3.3.0

pom.xml
=> [KARAF-7759] Upgrade maven-remote-resources-plugin to 3.1.0

pom.xml
=> [KARAF-7758]: Upgrade maven-surefire-plugin to 3.1.2

pom.xml
=> [KARAF-7757] Upgrade maven-enforcer-plugin to 3.4.1

pom.xml
=> [KARAF-7755]: Upgrade maven-compiler-plugin to 3.11.0

examples/karaf-soap-example/karaf-soap-example-blueprint/pom.xml, examples/karaf-soap-example/karaf-soap-example-scr/pom.xml, features/core/pom.xml, jaas/modules/pom.xml, pom.xml, scheduler/pom.xml, services/interceptor/impl/pom.xml, tooling/karaf-maven-plugin/pom.xml, tooling/karaf-maven-plugin/src/it/test-feature-use-version-range-transfer-properties/transitive/pom.xml
=> [KARAF-7764] Enforce Java 11 build runtime

pom.xml
=> [KARAF-7762] Upgrade build-helper-maven-plugin to 3.4.0

pom.xml
see https://issues.apache.org/jira/browse/KARAF-7852
=> KARAF-7852: Upgrade to commons-pool2 2.12.0

assemblies/features/specs/src/main/feature/feature.xml, pom.xml
Upgrades the following dependencies:
- snakeyaml from 1.33 to 2.2
- jackson from 2.14.1 to 2.17.2
=> [KARAF-7854] Upgrade to jackson 2.17.2

manual/src/main/asciidoc/user-guide/failover.adoc
Fixes a broken Cellar link the the failover docs.
=> Fix broken Cellar link

features/core/src/test/java/org/apache/karaf/features/internal/service/FeaturesValidationTest.java, itests/test/src/test/java/org/apache/karaf/itests/XATest.java
We have two typos, fix them up.
=> Remove superfluous semicolons

pom.xml
https://github.com/apache/mina-sshd/blob/master/docs/changes/2.15.0.md
=> [KARAF-7961]: Bump SSHD to 2.15.0

jaas/modules/src/main/java/org/apache/karaf/jaas/modules/AbstractKarafLoginModule.java
An ordered set ensure the UserPrincipal is always first
=> [KARAF-6158] Update AbstractKarafLoginModule to use an ordered Set

archetypes/assembly/src/main/resources/archetype-resources/pom.xml, assemblies/apache-karaf-minimal/pom.xml, assemblies/apache-karaf/pom.xml, assemblies/features/enterprise/pom.xml, assemblies/features/specs/pom.xml, assemblies/features/standard/pom.xml, examples/karaf-docker-example/karaf-docker-example-dynamic-dist/pom.xml, examples/karaf-docker-example/karaf-docker-example-static-dist/pom.xml, itests/test/src/test/java/org/apache/karaf/itests/mavenresolver/MavenResolverRegisteredBeforeConfigAdminTest.java, itests/test/src/test/java/org/apache/karaf/itests/mavenresolver/MavenResolverRegisteredOnlyAfterConfigAdminTest.java, main/pom.xml, management/server/pom.xml, management/server/src/main/java/org/apache/karaf/management/ConnectorServerFactory.java, management/server/src/main/java/org/apache/karaf/management/RmiRegistryFactory.java, management/server/src/main/java/org/apache/karaf/management/internal/Activator.java, pom.xml, specs/java.xml.ws/pom.xml, specs/java.xml/pom.xml, specs/locator/pom.xml
I have to refactor the JMX connector to work with any Java version.
=> KARAF-7889: Upgrade to Apache POM 35 and target Java SE 11

jaas/modules/src/main/java/org/apache/karaf/jaas/modules/impl/Activator.java, jaas/modules/src/main/java/org/apache/karaf/jaas/modules/ldap/LDAPBackingEngine.java, jaas/modules/src/main/java/org/apache/karaf/jaas/modules/ldap/LDAPBackingEngineFactory.java, jaas/modules/src/main/java/org/apache/karaf/jaas/modules/ldap/LDAPCache.java, jaas/modules/src/main/java/org/apache/karaf/jaas/modules/ldap/LDAPLoginModule.java, jaas/modules/src/main/java/org/apache/karaf/jaas/modules/ldap/LDAPPubkeyLoginModule.java, jaas/modules/src/test/java/org/apache/karaf/jaas/modules/ldap/LdapCacheTest.java, jaas/modules/src/test/resources/org/apache/karaf/jaas/modules/ldap/ldap.properties, jaas/modules/src/test/resources/org/apache/karaf/jaas/modules/ldap/ldap_badref.properties
- Add metrics to the LDAPCache object
- Fix unit test to _not_ disable cache
- Update unit test to verify metrics counts and caching are working
=> [karaf-4.4.x][KARAF-7671] Fix LDAP cache handling so it does not reset on every login attempt
